//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conan.VisualStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conan.VisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan extension: invalid conan executable.
        /// </summary>
        internal static string invalid_exe {
            get {
                return ResourceManager.GetString("invalid_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conan executable path is not set and Conan executable wasn&apos;t found automatically. Please set it up in the Tools → Settings → Conan menu..
        /// </summary>
        internal static string no_conan_exe {
            get {
                return ResourceManager.GetString("no_conan_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to locate conanfile directory!.
        /// </summary>
        internal static string no_conanfile_directory {
            get {
                return ResourceManager.GetString("no_conanfile_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C++ project with a conan file must be selected..
        /// </summary>
        internal static string no_cpp_project {
            get {
                return ResourceManager.GetString("no_cpp_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract conan project!.
        /// </summary>
        internal static string unable_to_extract {
            get {
                return ResourceManager.GetString("unable_to_extract", resourceCulture);
            }
        }
    }
}
