// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Conan.VisualStudio
{
    static class Vsix
    {
        public const string Id = "VSConanPackage.cab4ca1d-6f42-438f-a2eb-ab74c8069056";
        public const string Name = "Conan Visual Studio Extension";
        public const string Description = @"The Conan Visual Studio Extention automates the use of the Conan C/C++ package manager for retrieving dependencies within Visual Studio projects.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Bincrafters";
        public const string Tags = "conan c c++ packaging dependency management bincrafters";
    }
}
