// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Conan.VisualStudio
{
    static class Vsix
    {
        public const string Id = "VSConanPackage.4d0379e2-2698-4e66-89de-6ead71165e9f";
        public const string Name = "Conan Visual Studio Extension";
        public const string Description = @"The Conan Visual Studio Extention automates the use of the Conan C/C++ package manager for retrieving dependencies within Visual Studio projects.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Conan";
        public const string Tags = "conan c c++ packaging dependency management";
    }
}
