// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Conan.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSConanPackageString = "33315c89-72dd-43bb-863c-561c1aa5ed54";
        public const string guidVSConanPackageCmdSetString = "614d6e2d-166a-4d8c-b047-1c2248bbef97";
        public const string guidImagesString = "96b705f3-a54e-4748-86e2-ae8eb2e35169";
        public static Guid guidVSConanPackage = new Guid(guidVSConanPackageString);
        public static Guid guidVSConanPackageCmdSet = new Guid(guidVSConanPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ConanMenu = 0x1010;
        public const int ConanMenuGroup = 0x1020;
        public const int AddConanDependsProjectId = 0x0100;
        public const int AddConanDependsSolutiontId = 0x0101;
        public const int ConanOptionsId = 0x0103;
        public const int ConanAboutId = 0x0104;
        public const int ConanSubmenu = 0x1023;
        public const int ConanSubmenuGroup = 0x1024;
        public const int ConanProjectGroup = 0x1025;
        public const int ConanSolutionGroup = 0x1026;
        public const int ConanItemGroup = 0x1027;
        public const int cmdidPackageListToolWindowCommand = 0x1021;
        public const int cmdidIntegrateIntoProjectCommand = 0x1022;
        public const int bmpPic1 = 0x0001;
        public const int conanIcon = 0x0002;
    }
}
